---
title: "Risk Factor Analysis"
output: 
  html_document:
    standalone: true
    self_contained: true
required_packages:  ['github://HBGD-UCB/longbowRiskFactors','github://jeremyrcoyle/skimr@vector_types', 'github://tlverse/delayed']
params:
  roles:
    value:
      - strata
      - id
      - W
      - A
      - Y
  data: 
    value: 
      type: 'web'
      uri: 'https://raw.githubusercontent.com/HBGD-UCB/longbowRiskFactors/master/inst/sample_data/birthwt_data.csv'
  nodes:
    value:
      strata: ['study_id']
      W: ['apgar1', 'apgar5', 'gagebrth', 'mage', 'meducyrs', 'sexn']
      A: ['parity_cat']
      Y: ['haz01']
  script_params:
    value:
      parallelize:
        input: checkbox
        value: FALSE
      baseline_level:
        input: 'character'
        value: "[1,2)"
  output_directory:
    value: ''

---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, message=FALSE, eval.after = 'fig.cap')
options(scipen=999)
```

```{r params, warning=FALSE, message=FALSE}
library(tltools)
library(longbowRiskFactors)
library(sl3)
library(tmle3)
data <- get_tl_data()
nodes <- get_tl_nodes()
library(future)
tl_params <- get_tl_params()

message(nodes)
message(tl_params)
if(tl_params$parallelize){
  
  workers=availableCores()/2
  plan(multicore, workers=workers)
} else {
  workers = 1
  plan(sequential)
}


```

```{r preprocessing}

# drop missing values
processed <- process_missing(data, nodes,complete_nodes = c("strata","A","Y"))
data <- processed$data
nodes <- processed$node_list

# convert character columns to factors
char_to_factor <-function(data){
  classes <- sapply(data,data.class)
  char_cols <- names(classes)[which(classes=="character")]
  set(data, , char_cols, data[,lapply(.SD, as.factor), .SDcols = char_cols])
}

char_to_factor(data)

#define learners
if(FALSE && length(nodes$W)>0){
  qlib <- make_learner_stack("Lrnr_mean",
                             "Lrnr_glm_fast",
                             "Lrnr_glmnet",
                             list("Lrnr_xgboost", nthread=1))

  glib <- make_learner_stack("Lrnr_mean",
                             "Lrnr_glmnet",
                             list("Lrnr_xgboost", nthread=1))



  # qlib <- glib <- make_learner_stack("Lrnr_mean")
  mn_metalearner <- make_learner(Lrnr_solnp, loss_function = loss_loglik_multinomial, learner_function = metalearner_linear_multinomial)
  metalearner <- make_learner(Lrnr_nnls)
  Q_learner <- make_learner(Lrnr_sl, qlib, metalearner)
  g_learner <- make_learner(Lrnr_sl, glib, mn_metalearner)
} else {
  Q_learner <- make_learner(Lrnr_glm)
  g_learner <- make_learner(Lrnr_mean)
}

learner_list <- list(Y=Q_learner, A=g_learner)
```

```{r stratified_tmle, message=FALSE}
baseline_level <- tl_params$baseline_level
if(is.null(baseline_level)||is.na(baseline_level)){
  baseline_level = NULL
}
results <- stratified_tmle(data, nodes, baseline_level, learner_list)
formatted_results <- format_results(results, data, nodes)
```

# Outcome Variable

**Outcome Variable:** `r nodes$Y`

# Predictor Variables

**Intervention Variable:** `r nodes$A`

**Adjustment Set:**

```{r print_adjustment_set, results = "asis"}
for(covariate in nodes$W){
  cat(sprintf("* %s\n",covariate))
}
```

## Methods Detail

**todo**

# Results Detail

## Results Plots
```{r plot_tsm}
tsm_plot(formatted_results)
```

```{r plot_rr}
rr_plot(formatted_results)
```

```{r plot_paf}
paf_plot(formatted_results)
```

```{r plot_par}
par_plot(formatted_results)
```

## Data Summary
```{r data_summary}
obs_counts <- get_obs_counts(data, nodes)
kable(obs_counts)
```

## Results Table
```{r results_tables, results="asis"}
parameter_types <- unique(formatted_results$type)
for(parameter_type in parameter_types){
  cat(sprintf("\n\n### Parameter: %s\n", parameter_type))
  subset <- formatted_results[type==parameter_type]
  subset$type = NULL
  subset$parameter = NULL
  k <- kable(subset)
  print(k)
}
```

```{r save_results}
if(params$output_directory!=""){
  results_file <- file.path(params$output_directory, "results.rdata")
  
  save(formatted_results, file=results_file)
}
```
